# Stage 1: Build the Angular app
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the Angular source code
COPY . .

# Build the Angular app
RUN npm run build

# Stage 2: Serve the React app using NGINX
FROM nginx:alpine

# Copy the Reaact app from the builder stage
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
