version: '3.8'

services:
  service-job-board-post:
  uild:
    context: ./service-job-board-post
    image: 148761657112.dkr.ecr.us-east-1.amazonaws.com/service-job-board-post:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=job_board_db
    networks:
      - job-board-network
    depends_on:
      - mysql

  service-job-board-user:
    context: ./service-job-board-user
    image: 148761657112.dkr.ecr.us-east-1.amazonaws.com/service-job-board-user:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=job_board_db
    networks:
      - job-board-network
    depends_on:
      - mysql

  frontend:
    image: 148761657112.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports:
      - "80:80"
    networks:
      - job-board-network

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=job_board_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - job-board-network

networks:
  job-board-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
