name: Deploy to ECS using Docker Compose

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      # Step 2: Set up Docker (Docker is pre-installed on GitHub runners)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 3: Build, tag, and push service-job-board-post image to ECR
      - name: Build, tag, and push service-job-board-post
        run: |
          docker compose -f docker-compose-prod.yml build service-job-board-post
          docker tag 148761657112.dkr.ecr.us-east-1.amazonaws.com/service-job-board-post:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-job-board-post:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-job-board-post:latest

      # Step 4: Build, tag, and push service-job-board-user image to ECR
      - name: Build, tag, and push service-job-board-user
        run: |
          docker compose -f docker-compose-prod.yml build service-job-board-user
          docker tag 148761657112.dkr.ecr.us-east-1.amazonaws.com/service-job-board-user:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-job-board-user:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/service-job-board-user:latest

      # Step 5: Build, tag, and push frontend image to ECR
      - name: Build, tag, and push frontend
        run: |
          docker compose -f docker-compose-prod.yml build frontend
          docker tag 148761657112.dkr.ecr.us-east-1.amazonaws.com/frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest

      # Step 6: Deploy to ECS using Docker Compose
      - name: Deploy to ECS using Docker Compose
        run: |
          docker context create ecs myecscontext
          docker context use myecscontext
          docker-compose -f docker-compose-prod.yml up
